/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
 
import controller.ControleBusca;
import model.Filme;
import model.Serie;
import model.Usuario;
import model.Video;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import java.util.List;
 
public class Busca extends javax.swing.JFrame {
 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Busca.class.getName());
    private ControleBusca c;
    private DefaultTableModel tableModel;
    private List<Video> resultados;
 
    public Busca() {
        initComponents();
        configurarTabela();
    }
 
    public void setUsuario(Usuario usuario) {
        c = new ControleBusca(this, usuario);
    }
 
    private void configurarTabela() {
        tableModel = new DefaultTableModel(
            new String[]{"Titulo", "Tipo", "Ano", "Detalhe"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
        jTable3.setModel(tableModel);
        jTable3.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblTituloBusca = new javax.swing.JLabel();
        txtNomeVideo = new javax.swing.JTextField();
        btnBuscarVideo = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();
        lblStatusBusca = new javax.swing.JLabel();
        btnVoltarPrincipal = new javax.swing.JButton();
        tblResultados = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloBusca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloBusca.setText("Buscar Videos");

        txtNomeVideo.setText("Digite o nome do  video");
        txtNomeVideo.addActionListener(this::txtNomeVideoActionPerformed);

        btnBuscarVideo.setText("Buscar");
        btnBuscarVideo.addActionListener(this::btnBuscarVideoActionPerformed);

        btnDetalhes.setText("Ver Detalhes");
        btnDetalhes.addActionListener(this::btnDetalhesActionPerformed);

        btnVoltarPrincipal.setText("Voltar");
        btnVoltarPrincipal.addActionListener(this::btnVoltarPrincipalActionPerformed);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResultados.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(btnDetalhes)
                            .addGap(230, 230, 230)
                            .addComponent(btnVoltarPrincipal))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBuscarVideo)
                                    .addGap(125, 125, 125)
                                    .addComponent(lblStatusBusca))
                                .addComponent(lblTituloBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNomeVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTituloBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblStatusBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalhes)
                    .addComponent(btnVoltarPrincipal))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeVideoActionPerformed
         btnBuscarVideoActionPerformed(evt);
    }//GEN-LAST:event_txtNomeVideoActionPerformed

    private void btnVoltarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPrincipalActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarPrincipalActionPerformed

    private void btnBuscarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVideoActionPerformed
         String termo = txtNomeVideo.getText().trim();
        if (termo.isEmpty() || termo.equals("Digite o nome do  video")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Digite um título para buscar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        resultados = c.buscarVideos(termo);
        tableModel.setRowCount(0);
        lblStatusBusca.setText("");
        if (resultados == null || resultados.isEmpty()) {
            lblStatusBusca.setText("Nenhum resultado.");
            return;
        }
        for (Video v : resultados) {
            String detalhe;
            if (v instanceof Filme) {
                detalhe = ((Filme) v).getDuracao() + " min";
            } else if (v instanceof Serie) {
                detalhe = ((Serie) v).getTemporadas() + " temporadas";
            } else {
                detalhe = "-";
            }
            tableModel.addRow(new Object[]{v.getTitulo(), v.getTipo(), v.getAnoLancamento(), detalhe});
        }
        lblStatusBusca.setText(resultados.size() + " resultado(s).");
    }//GEN-LAST:event_btnBuscarVideoActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        int indiceSelecionado = jTable3.getSelectedRow();
        c.abrirDetalhes(indiceSelecionado, resultados);
    }//GEN-LAST:event_btnDetalhesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new Busca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVideo;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnVoltarPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblStatusBusca;
    private javax.swing.JLabel lblTituloBusca;
    private javax.swing.JScrollPane tblResultados;
    private javax.swing.JTextField txtNomeVideo;
    // End of variables declaration//GEN-END:variables
}
