/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
 
import controller.ControleDetalhesVideo;
import model.Filme;
import model.ListaReproducao;
import model.Serie;
import model.Usuario;
import model.Video;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ariel
 */
public class DetalhesVideo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetalhesVideo.class.getName());

    private ControleDetalhesVideo c;
    private Video video;
    private Usuario usuario;
 
    public DetalhesVideo() {
        initComponents();
    }
 
    public void setVideo(Video video) {
        this.video = video;
        preencherDados();
        verificarSetup();
    }
 
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        verificarSetup();
    }
 
    private void verificarSetup() {
        if (video != null && usuario != null) {
            c = new ControleDetalhesVideo(this, video, usuario);
            btnCurtir.setText(c.isCurtido() ? "Descurtir" : "Curtir");
            lblCurtidas.setText("Curtidas: " + c.contarCurtidas());
        }
    }
 
    private void preencherDados() {
        if (video == null) return;
        lblTitulo.setText("Titulo: " + video.getTitulo());
        lblTitulo2.setText("Tipo: " + video.getTipo());
        lblAno.setText("Ano: " + video.getAnoLancamento());
        txtDescricao.setText(video.getDescricao());
        txtDescricao.setEditable(false);
        txtDescricao.setLineWrap(true);
        txtDescricao.setWrapStyleWord(true);
        if (video instanceof Filme) {
            lblDetalhe1.setText("Duracao: " + ((Filme) video).getDuracao() + " min");
        } else if (video instanceof Serie) {
            lblDetalhe1.setText("Temporadas: " + ((Serie) video).getTemporadas());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblCurtidas = new javax.swing.JLabel();
        lblDetalhe1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnCurtir = new javax.swing.JButton();
        btnFavorito = new javax.swing.JButton();
        btnAdicionarLista = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        jLabel2.setText("Título");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Título:");

        lblAno.setText("Ano:");

        lblTitulo2.setText("Tipo:");

        lblCurtidas.setText("Curtidas: 0");

        lblDetalhe1.setText("Detalhes:");

        jLabel1.setText("Descrição");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        btnCurtir.setText("Curtir");
        btnCurtir.addActionListener(this::btnCurtirActionPerformed);

        btnFavorito.setText("Favoritar");
        btnFavorito.addActionListener(this::btnFavoritoActionPerformed);

        btnAdicionarLista.setText("Add na Lista");
        btnAdicionarLista.addActionListener(this::btnAdicionarListaActionPerformed);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCurtir)
                                .addGap(211, 211, 211)
                                .addComponent(btnAdicionarLista))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(lblCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnFavorito)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVoltar))))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDetalhe1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDetalhe1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCurtir)
                    .addComponent(btnAdicionarLista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFavorito)
                    .addComponent(btnVoltar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtirActionPerformed
        if (c.isCurtido()) {
        c.descurtir();
        btnCurtir.setText("Curtir");
    } else {
        c.curtir();
        btnCurtir.setText("Descurtir");
    }
    lblCurtidas.setText("Curtidas: " + c.contarCurtidas());
    }//GEN-LAST:event_btnCurtirActionPerformed

    private void btnFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritoActionPerformed
      c.adicionarFavorito();
    }//GEN-LAST:event_btnFavoritoActionPerformed

    private void btnAdicionarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarListaActionPerformed
        List<ListaReproducao> listas = c.listarListas();
    if (listas == null || listas.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Voce nao tem listas criadas.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    String[] nomes = listas.stream().map(ListaReproducao::getNomeLista).toArray(String[]::new);
    String escolha = (String) JOptionPane.showInputDialog(this, "Escolha uma lista:", "Adicionar a lista",
            JOptionPane.PLAIN_MESSAGE, null, nomes, nomes[0]);
    if (escolha != null) {
        int idLista = listas.stream()
                .filter(l -> l.getNomeLista().equals(escolha))
                .findFirst().get().getIdLista();
        c.adicionarNaLista(idLista);
    }
    }//GEN-LAST:event_btnAdicionarListaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DetalhesVideo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarLista;
    private javax.swing.JButton btnCurtir;
    private javax.swing.JButton btnFavorito;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCurtidas;
    private javax.swing.JLabel lblDetalhe1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTextArea txtDescricao;
    // End of variables declaration//GEN-END:variables
}
